apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tamuhack-prod-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name:  tamuhack-static-ip
spec:
  rules:
  - host: register.tamuhack.com
    http:
      paths:
      - backend:
          serviceName: hiss-nodeport-service
          servicePort: 9000
  - host: tamuhack.com
    http:
      paths:
      - backend:
          serviceName: moo-nodeport-service
          servicePort: 9001
