steps:
# This step deploys the new version of our container image
# in the barnyard Kubernetes Engine cluster.
- name: 'gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'apply'
  - '-f'
  - 'barnyard.yaml'
  - '-f'
  - 'hiss.yaml'
  - '-f'
  - 'moo.yaml'
  - '-f'
  - 'kube-slack.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=tamuhack-prod-cluster'
